try{
    const result=10/0;
    console.log(result);
}
catch(error){
    console.error('Error occured:',error);
}